#!/bin/bash
clear
printf "\e[0m\e[92m                                            HI\e[0m\n"
echo
echo
printf "\e[0m\e[92m                                  I CREATED A TOOL NGROK\e[0m\n"
echo
echo
printf "\e[0m\e[92m                          ███╗░░██╗░██████╗░██████╗░░█████╗░██╗░░██╗\e[0m\n"
printf "\e[0m\e[92m                          ████╗░██║██╔════╝░██╔══██╗██╔══██╗██║░██╔╝\e[0m\n"
printf "\e[0m\e[92m                          ██╔██╗██║██║░░██╗░██████╔╝██║░░██║█████═╝░\e[0m\n"
printf "\e[0m\e[92m                          ██║╚████║██║░░╚██╗██╔══██╗██║░░██║██╔═██╗░\e[0m\n"
printf "\e[0m\e[92m                          ██║░╚███║╚██████╔╝██║░░██║╚█████╔╝██║░╚██╗\e[0m\n"
printf "\e[0m\e[92m                          ╚═╝░░╚══╝░╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝\e[0m\n"
echo
echo
printf "\e[0m\e[92m                                       NAME ~; PRINCE GUTIERREZ\e[0m\n"
echo
echo
printf "\e[0m\e[92m                                    CODED BY PENTESTRATER12\e[0m\n"
echo
echo
printf "\e[0m\e[92m                                SUBSCRIBE NY YOUTUBE CHANNEL [PENTESTRATER12]1\e[0m\n"
echo
echo
printf "\e[0m\e[92m                          THIS TOOL CAN HELP YOU INSTALL NGROK AND GET NGROK LINK WITH ON TOOL\e[0m\n"
echo   
echo 
printf "\e[0m\e[92m                       PLEASE SUPPORT ME SUBSCRIBE MY YOUTUBE CHANNEL MY FB ACCOUNT https://www.facebook.com/profile.php?id=100068954811075\e[0m\n"
read -p "PRESS ENTER TO BACK ON NGROK " ENTER
if [ $ENTER == "U" ]; then
cd $HOME && cd NGROK && bash ngrok.sh
exit
