#!/bin/bash
clear
./ngrok authtoken 1xUCUKPKyXqHKUp3s0cM0nY63Fx_61CPJyXiVSQKFMsaj6MFm
clear
read -p "PRESS ENTER TO CONTINUE " Prinxe
clear
echo -e $red ███╗░░██╗░██████╗░██████╗░░█████╗░██╗░░██╗
echo -e $red ████╗░██║██╔════╝░██╔══██╗██╔══██╗██║░██╔╝
echo -e $red ██╔██╗██║██║░░██╗░██████╔╝██║░░██║█████═╝░
echo -e $red ██║╚████║██║░░╚██╗██╔══██╗██║░░██║██╔═██╗░
echo -e $red ██║░╚███║╚██████╔╝██║░░██║╚█████╔╝██║░╚██╗
echo -e $red ╚═╝░░╚══╝░╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝ v11.0
read -p "🇵​​​​​🇷​​​​​🇪​​​​​🇸​​​​​🇸​​​​​ 🇪​​​​​🇳​​​​​🇹​​​​​🇪​​​​​🇷​​​​​ 🇹​​​​​🇴​​​​​ 🇨​​​​​🇴​​​​​🇳​​​​​🇹​​​​​🇮​​​​​🇳​​​​​🇺​​​​​🇪​​​​​ " ENTER
echo -e $red ENTER 4 NUMBER PORTS
read -p "ENTER PORT: " hacker
cd $HOME && cd NGROK && ./ngrok http $hacker
sleep 1
exit
